import { BigHead } from '@bigheads/core';

const avatars = [
  <BigHead
    accessory="none"
    body="chest"
    circleColor="blue"
    clothing="dress"
    clothingColor="red"
    eyebrows="angry"
    eyes="content"
    faceMask
    faceMaskColor="black"
    facialHair="none2"
    hair="bun"
    hairColor="black"
    hat="none3"
    hatColor="green"
    lashes={false}
    lipColor="pink"
    mask
    mouth="open"
    skinTone="red"
  />,
  <BigHead
    accessory="roundGlasses"
    body="breasts"
    circleColor="blue"
    clothing="vneck"
    clothingColor="white"
    eyebrows="angry"
    eyes="wink"
    faceMask
    faceMaskColor="red"
    facialHair="none"
    hair="none"
    hairColor="blonde"
    hat="beanie"
    hatColor="blue"
    lashes
    lipColor="red"
    mask
    mouth="sad"
    skinTone="yellow"
  />,
  <BigHead
    accessory="none"
    body="breasts"
    circleColor="blue"
    clothing="naked"
    clothingColor="white"
    eyebrows="angry"
    eyes="content"
    faceMask
    faceMaskColor="green"
    facialHair="mediumBeard"
    hair="buzz"
    hairColor="black"
    hat="none4"
    hatColor="white"
    lashes={false}
    lipColor="pink"
    mask
    mouth="sad"
    skinTone="dark"
  />,
  <BigHead
    accessory="shades"
    body="breasts"
    circleColor="blue"
    clothing="tankTop"
    clothingColor="green"
    eyebrows="concerned"
    eyes="wink"
    faceMask
    faceMaskColor="blue"
    facialHair="none3"
    graphic="redwood"
    hair="long"
    hairColor="pink"
    hat="none3"
    hatColor="green"
    lashes
    lipColor="turqoise"
    mask
    mouth="grin"
    skinTone="yellow"
  />,
  <BigHead
    accessory="roundGlasses"
    body="breasts"
    circleColor="blue"
    clothing="dressShirt"
    clothingColor="red"
    eyebrows="leftLowered"
    eyes="content"
    faceMask
    faceMaskColor="red"
    facialHair="none"
    hair="short"
    hairColor="orange"
    hat="none5"
    hatColor="red"
    lashes
    lipColor="purple"
    mask
    mouth="lips"
    skinTone="yellow"
  />,
  <BigHead
    accessory="roundGlasses"
    body="chest"
    circleColor="blue"
    clothing="shirt"
    clothingColor="black"
    eyebrows="leftLowered"
    eyes="wink"
    faceMask
    faceMaskColor="green"
    facialHair="none"
    hair="long"
    hairColor="pink"
    hat="turban"
    hatColor="blue"
    lashes={false}
    lipColor="green"
    mask
    mouth="lips"
    skinTone="dark"
  />,
  <BigHead
    accessory="tinyGlasses"
    body="breasts"
    circleColor="blue"
    clothing="dressShirt"
    clothingColor="white"
    eyebrows="serious"
    eyes="normal"
    faceMask
    faceMaskColor="black"
    facialHair="mediumBeard"
    hair="bob"
    hairColor="blonde"
    hat="none2"
    hatColor="black"
    lashes
    lipColor="purple"
    mask
    mouth="openSmile"
    skinTone="light"
  />,
  <BigHead
    accessory="tinyGlasses"
    body="chest"
    circleColor="blue"
    clothing="shirt"
    clothingColor="white"
    eyebrows="leftLowered"
    eyes="dizzy"
    faceMask
    faceMaskColor="blue"
    facialHair="none3"
    hair="balding"
    hairColor="blonde"
    hat="none3"
    hatColor="green"
    lashes
    lipColor="turqoise"
    mask
    mouth="grin"
    skinTone="black"
  />,
  <BigHead
    accessory="none"
    body="chest"
    circleColor="blue"
    clothing="dressShirt"
    clothingColor="green"
    eyebrows="leftLowered"
    eyes="dizzy"
    faceMask
    faceMaskColor="green"
    facialHair="none"
    hair="buzz"
    hairColor="black"
    hat="beanie"
    hatColor="blue"
    lashes
    lipColor="pink"
    mask
    mouth="grin"
    skinTone="yellow"
  />,
  <BigHead
    accessory="tinyGlasses"
    body="chest"
    circleColor="blue"
    clothing="shirt"
    clothingColor="red"
    eyebrows="serious"
    eyes="squint"
    faceMask
    faceMaskColor="red"
    facialHair="none"
    hair="short"
    hairColor="brown"
    hat="beanie"
    hatColor="blue"
    lashes={false}
    lipColor="pink"
    mask
    mouth="openSmile"
    skinTone="light"
  />,
  <BigHead
    accessory="shades"
    body="chest"
    circleColor="blue"
    clothing="naked"
    clothingColor="black"
    eyebrows="leftLowered"
    eyes="wink"
    faceMask
    faceMaskColor="blue"
    facialHair="none3"
    hair="none"
    hairColor="pink"
    hat="beanie"
    hatColor="white"
    lashes={false}
    lipColor="turqoise"
    mask
    mouth="open"
    skinTone="red"
  />,
  <BigHead
    accessory="tinyGlasses"
    body="breasts"
    circleColor="blue"
    clothing="tankTop"
    clothingColor="blue"
    eyebrows="leftLowered"
    eyes="normal"
    faceMask
    faceMaskColor="red"
    facialHair="none"
    hair="bob"
    hairColor="orange"
    hat="none5"
    hatColor="white"
    lashes={false}
    lipColor="pink"
    mask
    mouth="grin"
    skinTone="brown"
  />,
  <BigHead
    accessory="roundGlasses"
    body="breasts"
    circleColor="blue"
    clothing="shirt"
    clothingColor="red"
    eyebrows="concerned"
    eyes="normal"
    faceMask
    faceMaskColor="white"
    facialHair="none2"
    hair="short"
    hairColor="blue"
    hat="turban"
    hatColor="white"
    lashes
    lipColor="purple"
    mask
    mouth="tongue"
    skinTone="yellow"
  />,
  <BigHead
    accessory="tinyGlasses"
    body="breasts"
    circleColor="blue"
    clothing="vneck"
    clothingColor="blue"
    eyebrows="serious"
    eyes="happy"
    faceMask
    faceMaskColor="white"
    facialHair="none2"
    hair="bun"
    hairColor="brown"
    hat="beanie"
    hatColor="green"
    lashes={false}
    lipColor="red"
    mask
    mouth="sad"
    skinTone="brown"
  />,
  <BigHead
    accessory="shades"
    body="chest"
    circleColor="blue"
    clothing="vneck"
    clothingColor="black"
    eyebrows="concerned"
    eyes="wink"
    faceMask
    faceMaskColor="green"
    facialHair="stubble"
    hair="none"
    hairColor="blue"
    hat="none3"
    hatColor="black"
    lashes
    lipColor="purple"
    mask
    mouth="serious"
    skinTone="yellow"
  />,
  <BigHead
    accessory="none"
    body="chest"
    circleColor="blue"
    clothing="dress"
    clothingColor="green"
    eyebrows="concerned"
    eyes="wink"
    faceMask
    faceMaskColor="red"
    facialHair="none"
    hair="afro"
    hairColor="black"
    hat="turban"
    hatColor="green"
    lashes
    lipColor="purple"
    mask
    mouth="lips"
    skinTone="brown"
  />,
  <BigHead
    accessory="tinyGlasses"
    body="chest"
    circleColor="blue"
    clothing="vneck"
    clothingColor="blue"
    eyebrows="raised"
    eyes="wink"
    faceMask
    faceMaskColor="white"
    facialHair="none2"
    hair="bob"
    hairColor="blue"
    hat="none2"
    hatColor="white"
    lashes
    lipColor="red"
    mask
    mouth="tongue"
    skinTone="yellow"
  />,
  <BigHead
    accessory="none"
    body="chest"
    circleColor="blue"
    clothing="tankTop"
    clothingColor="black"
    eyebrows="serious"
    eyes="happy"
    faceMask
    faceMaskColor="white"
    facialHair="none"
    hair="buzz"
    hairColor="black"
    hat="none4"
    hatColor="white"
    lashes
    lipColor="turqoise"
    mask
    mouth="sad"
    skinTone="brown"
  />,
  <BigHead
    accessory="shades"
    body="chest"
    circleColor="blue"
    clothing="shirt"
    clothingColor="green"
    eyebrows="raised"
    eyes="dizzy"
    faceMask
    faceMaskColor="black"
    facialHair="none3"
    hair="bob"
    hairColor="brown"
    hat="none5"
    hatColor="red"
    lashes
    lipColor="red"
    mask
    mouth="grin"
    skinTone="red"
  />,
  <BigHead
    accessory="none"
    body="chest"
    circleColor="blue"
    clothing="shirt"
    clothingColor="white"
    eyebrows="raised"
    eyes="heart"
    faceMask
    faceMaskColor="red"
    facialHair="none"
    hair="long"
    hairColor="blonde"
    hat="none5"
    hatColor="white"
    lashes={false}
    lipColor="turqoise"
    mask
    mouth="grin"
    skinTone="red"
  />,
];

export default avatars;
